baseURL = 'tyc.tw'
languageCode = 'en-us'
title = "Johnny's"
theme = "dario"

copyright = "Copyright Â© 2025 Johnny Chuang. All rights reserved."

# --- Google Analytics Service --
[serviecs]
    [services.googleAnalytics]
        ID = "G-ZEY9B2T7QK"